### ISSUE TITLE
Cannot print imap commands

### ISSUE THREAD

**Issue by xmkevin** [jpillora/go-tcp-proxy#7]
I use it to redirect imap ssl connections, but I the buffer cannot printed correctly, what's the reason ?
tks. go-tcp-proxy -l localhost:993 -r imap.gmail.com:993 -vv

**Comment by jpillora** [comment]
IMAP over 993 is generally encrypted. So you're seeing the ciphertext
whereas you want the plaintext. You could use a TCP port instead or strip
TLS
