### ISSUE TITLE
docker unix sock proxy ?

### ISSUE THREAD

**Issue by llitfkitfk** [jpillora/go-tcp-proxy#8]

**Comment by jpillora** [comment]
https://github.com/jpillora/sockfwd

**Comment by jpillora** [comment]
What are you trying to do?

**Comment by llitfkitfk** [comment]
@jpillora  do like this https://github.com/containerize/docker-proxy but want to do it with golang

**Comment by jpillora** [comment]
you don't need to proxy. this is a built-in docker option:

https://docs.docker.com/engine/reference/commandline/dockerd/#examples

**Comment by llitfkitfk** [comment]
@jpillora I know, but daemon need to reload
